# Generated by Django 3.1.1 on 2020-10-29 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('instruction', models.TextField(blank=True, max_length=500, null=True)),
                ('file', models.FileField(blank=True, default='profile pic.jpg', null=True, upload_to='assignments/')),
                ('points', models.PositiveSmallIntegerField(max_length=100)),
                ('due_date', models.DateField()),
                ('assigning_date', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.assignment')),
                ('class_room', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classroom')),
            ],
        ),
    ]
