# Generated by Django 3.1.3 on 2021-07-07 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidFinalMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_marks', models.IntegerField(blank=True, default=0, help_text='Final term marks', null=True)),
                ('mid_marks', models.IntegerField(blank=True, default=0, help_text='Mid term marks', null=True)),
                ('class_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.student')),
            ],
        ),
    ]
