# Generated by Django 3.1.1 on 2020-10-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_assignment_classinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='points',
            field=models.CharField(choices=[('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], default=100, max_length=100, null=True),
        ),
    ]
