# Generated by Django 3.1.3 on 2020-12-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20201124_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='class_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classroom'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='student_key',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
