# Generated by Django 3.1.3 on 2021-07-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_midfinalmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='midfinalmarks',
            name='final_marks_out_of',
            field=models.IntegerField(blank=True, default=0, help_text='Final term total marks', null=True),
        ),
        migrations.AddField(
            model_name='midfinalmarks',
            name='mid_marks_out_of',
            field=models.IntegerField(blank=True, default=0, help_text='Mid term total marks', null=True),
        ),
        migrations.AlterField(
            model_name='midfinalmarks',
            name='final_marks',
            field=models.IntegerField(blank=True, default=0, help_text='Final term obtained marks', null=True),
        ),
        migrations.AlterField(
            model_name='midfinalmarks',
            name='mid_marks',
            field=models.IntegerField(blank=True, default=0, help_text='Mid term obtained marks', null=True),
        ),
    ]
