# Generated by Django 3.1.1 on 2020-10-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20201030_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
