# Generated by Django 3.1.3 on 2020-12-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20201208_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='title_image',
            field=models.ImageField(blank=True, default='class Title image.jpg', null=True, upload_to='classTitleImages/'),
        ),
    ]
