# Generated by Django 3.1.3 on 2021-06-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20210624_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('files', models.FileField(blank=True, upload_to='files/lectures/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('class_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classroom')),
            ],
        ),
    ]
