# Generated by Django 3.1.3 on 2021-02-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20201216_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='title_image',
            field=models.ImageField(blank=True, default='classTitle image.jpg', null=True, upload_to='classTitleImages/'),
        ),
    ]
