# Generated by Django 3.1.1 on 2020-10-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20201030_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
