# Generated by Django 3.1.3 on 2021-02-20 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_announcement_class_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcement_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
