# Generated by Django 3.1.3 on 2020-11-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20201101_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, default='profile pic.jpg', null=True, upload_to='t_assignments/'),
        ),
    ]
