# Generated by Django 3.1.3 on 2021-02-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_announcement_announcement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_file',
            field=models.FileField(blank=True, null=True, upload_to='files/announcement_file/'),
        ),
    ]
