# Generated by Django 3.1.3 on 2020-11-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_auto_20201107_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, default='profile pic.jpg', null=True, upload_to='files/t_assignments/'),
        ),
    ]
