# Generated by Django 3.1.3 on 2021-02-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_auto_20210221_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_file',
            field=models.FileField(blank=True, upload_to='files/announcement_file/'),
        ),
    ]
