# Generated by Django 3.1.3 on 2020-11-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_auto_20201107_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/t_assignments/'),
        ),
    ]
