# Generated by Django 3.1.3 on 2021-03-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_auto_20210320_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
