# Generated by Django 3.1.3 on 2021-04-01 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_auto_20210330_1637'),
        ('classes', '0005_auto_20210214_1656'),
    ]

    operations = [
    ]
