# Generated by Django 3.1.3 on 2021-04-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_auto_20210330_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assigning_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
