# Generated by Django 3.1.3 on 2021-04-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0018_auto_20210401_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
