# Generated by Django 3.1.3 on 2021-04-06 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0020_auto_20210404_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='class_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='classes.classroom'),
        ),
    ]
