# Generated by Django 3.1.3 on 2021-04-12 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0021_auto_20210406_1627'),
        ('classes', '0018_merge_20210331_1730'),
    ]

    operations = [
    ]
