# Generated by Django 3.1.3 on 2021-03-11 19:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internetforum', '0002_comment_downvote_upvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='detail',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
