# Generated by Django 3.1.3 on 2021-04-03 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0018_merge_20210331_1730'),
        ('chat', '0002_auto_20210331_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='classdata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classdata', to='classes.classroom'),
        ),
    ]
