# Generated by Django 3.1.3 on 2021-04-10 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0018_merge_20210331_1730'),
        ('chat', '0004_remove_message_classdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='class_room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classroom'),
        ),
    ]
