# Generated by Django 3.1.3 on 2021-04-10 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0018_merge_20210331_1730'),
        ('chat', '0006_auto_20210409_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='class_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='classes.classroom'),
        ),
    ]
