# Generated by Django 3.1.3 on 2020-11-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Lecturer', 'Lecturer'), ('Student', 'Student')], default='Student', max_length=100),
        ),
    ]
