# Generated by Django 3.1.3 on 2021-04-08 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0021_auto_20210406_1627'),
        ('quizes', '0003_quiz_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='class_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
